# python version 1.0						DO NOT EDIT
#
# Generated by smidump version 0.4.8:
#
#   smidump -f python MYMIB

FILENAME = "MYMIB.mib"

MIB = {
    "moduleName" : "MYMIB",

    "MYMIB" : {
        "nodetype" : "module",
        "language" : "SMIv2",
        "organization" :    
            """PUCRS""",
        "contact" : 
            """admin@localhost""",
        "description" :
            """MY MIB""",
        "revisions" : (
            {
                "date" : "2024-06-29 00:00",
                "description" :
                    """Initial version.""",
            },
        ),
        "identity node" : "myMIB",
    },

    "imports" : (
        {"module" : "SNMPv2-CONF", "name" : "OBJECT-GROUP"},
        {"module" : "SNMPv2-SMI", "name" : "OBJECT-TYPE"},
        {"module" : "SNMPv2-SMI", "name" : "experimental"},
        {"module" : "SNMPv2-TC", "name" : "DisplayString"},
    ),

    "nodes" : {
        "myMIB" : {
            "nodetype" : "node",
            "moduleName" : "MYMIB",
            "oid" : "1.3.6.1.3.1234",
            "status" : "current",
        }, # node
        "myObjects" : {
            "nodetype" : "node",
            "moduleName" : "MYMIB",
            "oid" : "1.3.6.1.3.1234.1",
        }, # node
        "httpRequestsTotal" : {
            "nodetype" : "scalar",
            "moduleName" : "MYMIB",
            "oid" : "1.3.6.1.3.1234.1.1",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """The total number of HTTP requests.""",
        }, # scalar
        "httpRequestsPerSecond" : {
            "nodetype" : "scalar",
            "moduleName" : "MYMIB",
            "oid" : "1.3.6.1.3.1234.1.2",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """The number of HTTP requests per second.""",
        }, # scalar
        "httpResponseTime" : {
            "nodetype" : "scalar",
            "moduleName" : "MYMIB",
            "oid" : "1.3.6.1.3.1234.1.3",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """The average HTTP response time in milliseconds.""",
        }, # scalar
        "httpActiveConnections" : {
            "nodetype" : "scalar",
            "moduleName" : "MYMIB",
            "oid" : "1.3.6.1.3.1234.1.4",
            "status" : "current",
            "syntax" : {
                "type" : { "module" :"", "name" : "Integer32"},
            },
            "access" : "readonly",
            "description" :
                """The number of active HTTP connections.""",
        }, # scalar
    }, # nodes

}
